/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.ide;

import org.xtext.avi.ide.AbstractPdfMkIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PdfMkIdeModule extends AbstractPdfMkIdeModule {
}
