/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Object Members Wrapper</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.avi.pdfMk.ColumnObjectMembersWrapper#getText <em>Text</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.ColumnObjectMembersWrapper#getTextObject <em>Text Object</em>}</li>
 * </ul>
 *
 * @see org.xtext.avi.pdfMk.PdfMkPackage#getColumnObjectMembersWrapper()
 * @model
 * @generated
 */
public interface ColumnObjectMembersWrapper extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.avi.pdfMk.StringObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference list.
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getColumnObjectMembersWrapper_Text()
   * @model containment="true"
   * @generated
   */
  EList<StringObject> getText();

  /**
   * Returns the value of the '<em><b>Text Object</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.avi.pdfMk.TextObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text Object</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text Object</em>' containment reference list.
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getColumnObjectMembersWrapper_TextObject()
   * @model containment="true"
   * @generated
   */
  EList<TextObject> getTextObject();

} // ColumnObjectMembersWrapper
