/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.avi.pdfMk.ColumnDefinition#isGlobalStyle <em>Global Style</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.ColumnDefinition#getKey <em>Key</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.ColumnDefinition#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.avi.pdfMk.PdfMkPackage#getColumnDefinition()
 * @model
 * @generated
 */
public interface ColumnDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Global Style</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Style</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Style</em>' attribute.
   * @see #setGlobalStyle(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getColumnDefinition_GlobalStyle()
   * @model
   * @generated
   */
  boolean isGlobalStyle();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.ColumnDefinition#isGlobalStyle <em>Global Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global Style</em>' attribute.
   * @see #isGlobalStyle()
   * @generated
   */
  void setGlobalStyle(boolean value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getColumnDefinition_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.ColumnDefinition#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.avi.pdfMk.ColumnObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference list.
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getColumnDefinition_Value()
   * @model containment="true"
   * @generated
   */
  EList<ColumnObject> getValue();

} // ColumnDefinition
