/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.avi.pdfMk.PdfMkPackage#getContent()
 * @model
 * @generated
 */
public interface Content extends EObject
{
} // Content
