/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.avi.pdfMk.ListObject#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.ListObject#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.ListObject#getElements <em>Elements</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.ListObject#getElemtens <em>Elemtens</em>}</li>
 * </ul>
 *
 * @see org.xtext.avi.pdfMk.PdfMkPackage#getListObject()
 * @model
 * @generated
 */
public interface ListObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getListObject_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.ListObject#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.avi.pdfMk.ListObjectPropertiesWrapper}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Properties</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getListObject_Properties()
   * @model containment="true"
   * @generated
   */
  EList<ListObjectPropertiesWrapper> getProperties();

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.avi.pdfMk.ListElements}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getListObject_Elements()
   * @model containment="true"
   * @generated
   */
  EList<ListElements> getElements();

  /**
   * Returns the value of the '<em><b>Elemtens</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.avi.pdfMk.ListElements}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elemtens</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elemtens</em>' containment reference list.
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getListObject_Elemtens()
   * @model containment="true"
   * @generated
   */
  EList<ListElements> getElemtens();

} // ListObject
