/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.avi.pdfMk.PdfMkFactory
 * @model kind="package"
 * @generated
 */
public interface PdfMkPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pdfMk";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/avi/PdfMk";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pdfMk";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PdfMkPackage eINSTANCE = org.xtext.avi.pdfMk.impl.PdfMkPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.DocDefinitionImpl <em>Doc Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.DocDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getDocDefinition()
   * @generated
   */
  int DOC_DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Roots</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_DEFINITION__ROOTS = 0;

  /**
   * The number of structural features of the '<em>Doc Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ElementImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.DocDefinition <em>Doc Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doc Definition</em>'.
   * @see org.xtext.avi.pdfMk.DocDefinition
   * @generated
   */
  EClass getDocDefinition();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.avi.pdfMk.DocDefinition#getRoots <em>Roots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Roots</em>'.
   * @see org.xtext.avi.pdfMk.DocDefinition#getRoots()
   * @see #getDocDefinition()
   * @generated
   */
  EAttribute getDocDefinition_Roots();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.avi.pdfMk.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.Element#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.xtext.avi.pdfMk.Element#getElement()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Element();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PdfMkFactory getPdfMkFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.DocDefinitionImpl <em>Doc Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.DocDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getDocDefinition()
     * @generated
     */
    EClass DOC_DEFINITION = eINSTANCE.getDocDefinition();

    /**
     * The meta object literal for the '<em><b>Roots</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOC_DEFINITION__ROOTS = eINSTANCE.getDocDefinition_Roots();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ElementImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__ELEMENT = eINSTANCE.getElement_Element();

  }

} //PdfMkPackage
