/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.avi.pdfMk.PdfMkPackage
 * @generated
 */
public interface PdfMkFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PdfMkFactory eINSTANCE = org.xtext.avi.pdfMk.impl.PdfMkFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Doc Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Doc Definition</em>'.
   * @generated
   */
  DocDefinition createDocDefinition();

  /**
   * Returns a new object of class '<em>String Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Object</em>'.
   * @generated
   */
  StringObject createStringObject();

  /**
   * Returns a new object of class '<em>Type Face Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Face Definition</em>'.
   * @generated
   */
  TypeFaceDefinition createTypeFaceDefinition();

  /**
   * Returns a new object of class '<em>Text Style Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text Style Definition</em>'.
   * @generated
   */
  TextStyleDefinition createTextStyleDefinition();

  /**
   * Returns a new object of class '<em>Italics Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Italics Definition</em>'.
   * @generated
   */
  ItalicsDefinition createItalicsDefinition();

  /**
   * Returns a new object of class '<em>Font Size Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Font Size Definition</em>'.
   * @generated
   */
  FontSizeDefinition createFontSizeDefinition();

  /**
   * Returns a new object of class '<em>Style Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Style Definition</em>'.
   * @generated
   */
  StyleDefinition createStyleDefinition();

  /**
   * Returns a new object of class '<em>Text Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text Object</em>'.
   * @generated
   */
  TextObject createTextObject();

  /**
   * Returns a new object of class '<em>Style Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Style Object</em>'.
   * @generated
   */
  StyleObject createStyleObject();

  /**
   * Returns a new object of class '<em>Style Objects</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Style Objects</em>'.
   * @generated
   */
  StyleObjects createStyleObjects();

  /**
   * Returns a new object of class '<em>Content Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content Object</em>'.
   * @generated
   */
  ContentObject createContentObject();

  /**
   * Returns a new object of class '<em>Content Objects</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content Objects</em>'.
   * @generated
   */
  ContentObjects createContentObjects();

  /**
   * Returns a new object of class '<em>Styles</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Styles</em>'.
   * @generated
   */
  Styles createStyles();

  /**
   * Returns a new object of class '<em>Content</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content</em>'.
   * @generated
   */
  Content createContent();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PdfMkPackage getPdfMkPackage();

} //PdfMkFactory
