/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.avi.pdfMk.PdfMkFactory
 * @model kind="package"
 * @generated
 */
public interface PdfMkPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pdfMk";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/avi/PdfMk";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pdfMk";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PdfMkPackage eINSTANCE = org.xtext.avi.pdfMk.impl.PdfMkPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.DocDefinitionImpl <em>Doc Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.DocDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getDocDefinition()
   * @generated
   */
  int DOC_DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_DEFINITION__CONTENT = 0;

  /**
   * The feature id for the '<em><b>Styles</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_DEFINITION__STYLES = 1;

  /**
   * The number of structural features of the '<em>Doc Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOC_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.StringObjectImpl <em>String Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.StringObjectImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStringObject()
   * @generated
   */
  int STRING_OBJECT = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_OBJECT__VALUE = 0;

  /**
   * The number of structural features of the '<em>String Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_OBJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.TypeFaceDefinitionImpl <em>Type Face Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.TypeFaceDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getTypeFaceDefinition()
   * @generated
   */
  int TYPE_FACE_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FACE_DEFINITION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FACE_DEFINITION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Type Face Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FACE_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.TextStyleDefinitionImpl <em>Text Style Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.TextStyleDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getTextStyleDefinition()
   * @generated
   */
  int TEXT_STYLE_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_STYLE_DEFINITION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_STYLE_DEFINITION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Text Style Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_STYLE_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ItalicsDefinitionImpl <em>Italics Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ItalicsDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getItalicsDefinition()
   * @generated
   */
  int ITALICS_DEFINITION = 4;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITALICS_DEFINITION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITALICS_DEFINITION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Italics Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITALICS_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.FontSizeDefinitionImpl <em>Font Size Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.FontSizeDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getFontSizeDefinition()
   * @generated
   */
  int FONT_SIZE_DEFINITION = 5;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONT_SIZE_DEFINITION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONT_SIZE_DEFINITION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Font Size Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONT_SIZE_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.StyleDefinitionImpl <em>Style Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.StyleDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyleDefinition()
   * @generated
   */
  int STYLE_DEFINITION = 6;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_DEFINITION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_DEFINITION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Style Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.WidthDefinitionImpl <em>Width Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.WidthDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getWidthDefinition()
   * @generated
   */
  int WIDTH_DEFINITION = 7;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIDTH_DEFINITION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIDTH_DEFINITION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Width Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIDTH_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ColumnGapDefintionImpl <em>Column Gap Defintion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ColumnGapDefintionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnGapDefintion()
   * @generated
   */
  int COLUMN_GAP_DEFINTION = 8;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_GAP_DEFINTION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_GAP_DEFINTION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Column Gap Defintion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_GAP_DEFINTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ColumnDefinitionImpl <em>Column Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ColumnDefinitionImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnDefinition()
   * @generated
   */
  int COLUMN_DEFINITION = 9;

  /**
   * The feature id for the '<em><b>Global Style</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_DEFINITION__GLOBAL_STYLE = 0;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_DEFINITION__KEY = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_DEFINITION__VALUE = 2;

  /**
   * The number of structural features of the '<em>Column Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.InnerColumnObjectImpl <em>Inner Column Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.InnerColumnObjectImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getInnerColumnObject()
   * @generated
   */
  int INNER_COLUMN_OBJECT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNER_COLUMN_OBJECT__VALUE = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNER_COLUMN_OBJECT__TEXT = 1;

  /**
   * The feature id for the '<em><b>Text Object</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNER_COLUMN_OBJECT__TEXT_OBJECT = 2;

  /**
   * The feature id for the '<em><b>Column</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNER_COLUMN_OBJECT__COLUMN = 3;

  /**
   * The number of structural features of the '<em>Inner Column Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INNER_COLUMN_OBJECT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ColumnObjectImpl <em>Column Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ColumnObjectImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnObject()
   * @generated
   */
  int COLUMN_OBJECT = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_OBJECT__VALUE = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_OBJECT__TEXT = 1;

  /**
   * The feature id for the '<em><b>Text Object</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_OBJECT__TEXT_OBJECT = 2;

  /**
   * The feature id for the '<em><b>Column</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_OBJECT__COLUMN = 3;

  /**
   * The feature id for the '<em><b>Inner Column</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_OBJECT__INNER_COLUMN = 4;

  /**
   * The number of structural features of the '<em>Column Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_OBJECT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.TextObjectImpl <em>Text Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.TextObjectImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getTextObject()
   * @generated
   */
  int TEXT_OBJECT = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__VALUE = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__TEXT = 1;

  /**
   * The feature id for the '<em><b>Style</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__STYLE = 2;

  /**
   * The feature id for the '<em><b>Font Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__FONT_SIZE = 3;

  /**
   * The feature id for the '<em><b>Alignment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__ALIGNMENT = 4;

  /**
   * The feature id for the '<em><b>Type Face</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__TYPE_FACE = 5;

  /**
   * The feature id for the '<em><b>Italics</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__ITALICS = 6;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT__WIDTH = 7;

  /**
   * The number of structural features of the '<em>Text Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_OBJECT_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ColumnTextObjectImpl <em>Column Text Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ColumnTextObjectImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnTextObject()
   * @generated
   */
  int COLUMN_TEXT_OBJECT = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_TEXT_OBJECT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Column Text Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_TEXT_OBJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.StyleObjectImpl <em>Style Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.StyleObjectImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyleObject()
   * @generated
   */
  int STYLE_OBJECT = 14;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECT__VALUE = 1;

  /**
   * The feature id for the '<em><b>Font Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECT__FONT_SIZE = 2;

  /**
   * The feature id for the '<em><b>Type Face</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECT__TYPE_FACE = 3;

  /**
   * The feature id for the '<em><b>Alignment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECT__ALIGNMENT = 4;

  /**
   * The feature id for the '<em><b>Italics</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECT__ITALICS = 5;

  /**
   * The number of structural features of the '<em>Style Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECT_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.StyleObjectsImpl <em>Style Objects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.StyleObjectsImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyleObjects()
   * @generated
   */
  int STYLE_OBJECTS = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECTS__VALUE = 0;

  /**
   * The number of structural features of the '<em>Style Objects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLE_OBJECTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ContentObjectImpl <em>Content Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ContentObjectImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getContentObject()
   * @generated
   */
  int CONTENT_OBJECT = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_OBJECT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Content Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_OBJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ContentObjectsImpl <em>Content Objects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ContentObjectsImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getContentObjects()
   * @generated
   */
  int CONTENT_OBJECTS = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_OBJECTS__VALUE = 0;

  /**
   * The number of structural features of the '<em>Content Objects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_OBJECTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.StylesImpl <em>Styles</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.StylesImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyles()
   * @generated
   */
  int STYLES = 18;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLES__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLES__VALUE = 1;

  /**
   * The number of structural features of the '<em>Styles</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.avi.pdfMk.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.avi.pdfMk.impl.ContentImpl
   * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getContent()
   * @generated
   */
  int CONTENT = 19;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.DocDefinition <em>Doc Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doc Definition</em>'.
   * @see org.xtext.avi.pdfMk.DocDefinition
   * @generated
   */
  EClass getDocDefinition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.avi.pdfMk.DocDefinition#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Content</em>'.
   * @see org.xtext.avi.pdfMk.DocDefinition#getContent()
   * @see #getDocDefinition()
   * @generated
   */
  EReference getDocDefinition_Content();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.avi.pdfMk.DocDefinition#getStyles <em>Styles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Styles</em>'.
   * @see org.xtext.avi.pdfMk.DocDefinition#getStyles()
   * @see #getDocDefinition()
   * @generated
   */
  EReference getDocDefinition_Styles();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.StringObject <em>String Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Object</em>'.
   * @see org.xtext.avi.pdfMk.StringObject
   * @generated
   */
  EClass getStringObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StringObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.StringObject#getValue()
   * @see #getStringObject()
   * @generated
   */
  EAttribute getStringObject_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.TypeFaceDefinition <em>Type Face Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Face Definition</em>'.
   * @see org.xtext.avi.pdfMk.TypeFaceDefinition
   * @generated
   */
  EClass getTypeFaceDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TypeFaceDefinition#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.TypeFaceDefinition#getKey()
   * @see #getTypeFaceDefinition()
   * @generated
   */
  EAttribute getTypeFaceDefinition_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TypeFaceDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.TypeFaceDefinition#getValue()
   * @see #getTypeFaceDefinition()
   * @generated
   */
  EAttribute getTypeFaceDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.TextStyleDefinition <em>Text Style Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Style Definition</em>'.
   * @see org.xtext.avi.pdfMk.TextStyleDefinition
   * @generated
   */
  EClass getTextStyleDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextStyleDefinition#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.TextStyleDefinition#getKey()
   * @see #getTextStyleDefinition()
   * @generated
   */
  EAttribute getTextStyleDefinition_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextStyleDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.TextStyleDefinition#getValue()
   * @see #getTextStyleDefinition()
   * @generated
   */
  EAttribute getTextStyleDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.ItalicsDefinition <em>Italics Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Italics Definition</em>'.
   * @see org.xtext.avi.pdfMk.ItalicsDefinition
   * @generated
   */
  EClass getItalicsDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.ItalicsDefinition#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.ItalicsDefinition#getKey()
   * @see #getItalicsDefinition()
   * @generated
   */
  EAttribute getItalicsDefinition_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.ItalicsDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.ItalicsDefinition#getValue()
   * @see #getItalicsDefinition()
   * @generated
   */
  EAttribute getItalicsDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.FontSizeDefinition <em>Font Size Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Font Size Definition</em>'.
   * @see org.xtext.avi.pdfMk.FontSizeDefinition
   * @generated
   */
  EClass getFontSizeDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.FontSizeDefinition#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.FontSizeDefinition#getKey()
   * @see #getFontSizeDefinition()
   * @generated
   */
  EAttribute getFontSizeDefinition_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.FontSizeDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.FontSizeDefinition#getValue()
   * @see #getFontSizeDefinition()
   * @generated
   */
  EAttribute getFontSizeDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.StyleDefinition <em>Style Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Style Definition</em>'.
   * @see org.xtext.avi.pdfMk.StyleDefinition
   * @generated
   */
  EClass getStyleDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StyleDefinition#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.StyleDefinition#getKey()
   * @see #getStyleDefinition()
   * @generated
   */
  EAttribute getStyleDefinition_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.avi.pdfMk.StyleDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.StyleDefinition#getValue()
   * @see #getStyleDefinition()
   * @generated
   */
  EReference getStyleDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.WidthDefinition <em>Width Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Width Definition</em>'.
   * @see org.xtext.avi.pdfMk.WidthDefinition
   * @generated
   */
  EClass getWidthDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.WidthDefinition#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.WidthDefinition#getKey()
   * @see #getWidthDefinition()
   * @generated
   */
  EAttribute getWidthDefinition_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.WidthDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.WidthDefinition#getValue()
   * @see #getWidthDefinition()
   * @generated
   */
  EAttribute getWidthDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.ColumnGapDefintion <em>Column Gap Defintion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Gap Defintion</em>'.
   * @see org.xtext.avi.pdfMk.ColumnGapDefintion
   * @generated
   */
  EClass getColumnGapDefintion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.ColumnGapDefintion#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.ColumnGapDefintion#getKey()
   * @see #getColumnGapDefintion()
   * @generated
   */
  EAttribute getColumnGapDefintion_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.ColumnGapDefintion#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.ColumnGapDefintion#getValue()
   * @see #getColumnGapDefintion()
   * @generated
   */
  EAttribute getColumnGapDefintion_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.ColumnDefinition <em>Column Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Definition</em>'.
   * @see org.xtext.avi.pdfMk.ColumnDefinition
   * @generated
   */
  EClass getColumnDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.ColumnDefinition#isGlobalStyle <em>Global Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Global Style</em>'.
   * @see org.xtext.avi.pdfMk.ColumnDefinition#isGlobalStyle()
   * @see #getColumnDefinition()
   * @generated
   */
  EAttribute getColumnDefinition_GlobalStyle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.ColumnDefinition#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.ColumnDefinition#getKey()
   * @see #getColumnDefinition()
   * @generated
   */
  EAttribute getColumnDefinition_Key();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.ColumnDefinition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.ColumnDefinition#getValue()
   * @see #getColumnDefinition()
   * @generated
   */
  EReference getColumnDefinition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.InnerColumnObject <em>Inner Column Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inner Column Object</em>'.
   * @see org.xtext.avi.pdfMk.InnerColumnObject
   * @generated
   */
  EClass getInnerColumnObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.InnerColumnObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.InnerColumnObject#getValue()
   * @see #getInnerColumnObject()
   * @generated
   */
  EAttribute getInnerColumnObject_Value();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.InnerColumnObject#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text</em>'.
   * @see org.xtext.avi.pdfMk.InnerColumnObject#getText()
   * @see #getInnerColumnObject()
   * @generated
   */
  EReference getInnerColumnObject_Text();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.InnerColumnObject#getTextObject <em>Text Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text Object</em>'.
   * @see org.xtext.avi.pdfMk.InnerColumnObject#getTextObject()
   * @see #getInnerColumnObject()
   * @generated
   */
  EReference getInnerColumnObject_TextObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.InnerColumnObject#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Column</em>'.
   * @see org.xtext.avi.pdfMk.InnerColumnObject#getColumn()
   * @see #getInnerColumnObject()
   * @generated
   */
  EReference getInnerColumnObject_Column();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.ColumnObject <em>Column Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Object</em>'.
   * @see org.xtext.avi.pdfMk.ColumnObject
   * @generated
   */
  EClass getColumnObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.ColumnObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.ColumnObject#getValue()
   * @see #getColumnObject()
   * @generated
   */
  EAttribute getColumnObject_Value();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.ColumnObject#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text</em>'.
   * @see org.xtext.avi.pdfMk.ColumnObject#getText()
   * @see #getColumnObject()
   * @generated
   */
  EReference getColumnObject_Text();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.ColumnObject#getTextObject <em>Text Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text Object</em>'.
   * @see org.xtext.avi.pdfMk.ColumnObject#getTextObject()
   * @see #getColumnObject()
   * @generated
   */
  EReference getColumnObject_TextObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.ColumnObject#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Column</em>'.
   * @see org.xtext.avi.pdfMk.ColumnObject#getColumn()
   * @see #getColumnObject()
   * @generated
   */
  EReference getColumnObject_Column();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.ColumnObject#getInnerColumn <em>Inner Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inner Column</em>'.
   * @see org.xtext.avi.pdfMk.ColumnObject#getInnerColumn()
   * @see #getColumnObject()
   * @generated
   */
  EReference getColumnObject_InnerColumn();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.TextObject <em>Text Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Object</em>'.
   * @see org.xtext.avi.pdfMk.TextObject
   * @generated
   */
  EClass getTextObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#getValue()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_Value();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#isText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#isText()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_Text();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#isStyle <em>Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Style</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#isStyle()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_Style();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#isFontSize <em>Font Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Font Size</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#isFontSize()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_FontSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#isAlignment <em>Alignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alignment</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#isAlignment()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_Alignment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#isTypeFace <em>Type Face</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Face</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#isTypeFace()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_TypeFace();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#isItalics <em>Italics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Italics</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#isItalics()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_Italics();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.TextObject#isWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.xtext.avi.pdfMk.TextObject#isWidth()
   * @see #getTextObject()
   * @generated
   */
  EAttribute getTextObject_Width();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.ColumnTextObject <em>Column Text Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Text Object</em>'.
   * @see org.xtext.avi.pdfMk.ColumnTextObject
   * @generated
   */
  EClass getColumnTextObject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.avi.pdfMk.ColumnTextObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.ColumnTextObject#getValue()
   * @see #getColumnTextObject()
   * @generated
   */
  EReference getColumnTextObject_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.StyleObject <em>Style Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Style Object</em>'.
   * @see org.xtext.avi.pdfMk.StyleObject
   * @generated
   */
  EClass getStyleObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StyleObject#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.StyleObject#getKey()
   * @see #getStyleObject()
   * @generated
   */
  EAttribute getStyleObject_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StyleObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.StyleObject#getValue()
   * @see #getStyleObject()
   * @generated
   */
  EAttribute getStyleObject_Value();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StyleObject#isFontSize <em>Font Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Font Size</em>'.
   * @see org.xtext.avi.pdfMk.StyleObject#isFontSize()
   * @see #getStyleObject()
   * @generated
   */
  EAttribute getStyleObject_FontSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StyleObject#isTypeFace <em>Type Face</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Face</em>'.
   * @see org.xtext.avi.pdfMk.StyleObject#isTypeFace()
   * @see #getStyleObject()
   * @generated
   */
  EAttribute getStyleObject_TypeFace();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StyleObject#isAlignment <em>Alignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alignment</em>'.
   * @see org.xtext.avi.pdfMk.StyleObject#isAlignment()
   * @see #getStyleObject()
   * @generated
   */
  EAttribute getStyleObject_Alignment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.StyleObject#isItalics <em>Italics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Italics</em>'.
   * @see org.xtext.avi.pdfMk.StyleObject#isItalics()
   * @see #getStyleObject()
   * @generated
   */
  EAttribute getStyleObject_Italics();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.StyleObjects <em>Style Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Style Objects</em>'.
   * @see org.xtext.avi.pdfMk.StyleObjects
   * @generated
   */
  EClass getStyleObjects();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.StyleObjects#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.StyleObjects#getValue()
   * @see #getStyleObjects()
   * @generated
   */
  EReference getStyleObjects_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.ContentObject <em>Content Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content Object</em>'.
   * @see org.xtext.avi.pdfMk.ContentObject
   * @generated
   */
  EClass getContentObject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.avi.pdfMk.ContentObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.ContentObject#getValue()
   * @see #getContentObject()
   * @generated
   */
  EReference getContentObject_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.ContentObjects <em>Content Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content Objects</em>'.
   * @see org.xtext.avi.pdfMk.ContentObjects
   * @generated
   */
  EClass getContentObjects();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.avi.pdfMk.ContentObjects#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.ContentObjects#getValue()
   * @see #getContentObjects()
   * @generated
   */
  EReference getContentObjects_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.Styles <em>Styles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Styles</em>'.
   * @see org.xtext.avi.pdfMk.Styles
   * @generated
   */
  EClass getStyles();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.Styles#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.Styles#getKey()
   * @see #getStyles()
   * @generated
   */
  EAttribute getStyles_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.avi.pdfMk.Styles#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.Styles#getValue()
   * @see #getStyles()
   * @generated
   */
  EReference getStyles_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.avi.pdfMk.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see org.xtext.avi.pdfMk.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.avi.pdfMk.Content#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.avi.pdfMk.Content#getKey()
   * @see #getContent()
   * @generated
   */
  EAttribute getContent_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.avi.pdfMk.Content#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.avi.pdfMk.Content#getValue()
   * @see #getContent()
   * @generated
   */
  EReference getContent_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PdfMkFactory getPdfMkFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.DocDefinitionImpl <em>Doc Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.DocDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getDocDefinition()
     * @generated
     */
    EClass DOC_DEFINITION = eINSTANCE.getDocDefinition();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOC_DEFINITION__CONTENT = eINSTANCE.getDocDefinition_Content();

    /**
     * The meta object literal for the '<em><b>Styles</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOC_DEFINITION__STYLES = eINSTANCE.getDocDefinition_Styles();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.StringObjectImpl <em>String Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.StringObjectImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStringObject()
     * @generated
     */
    EClass STRING_OBJECT = eINSTANCE.getStringObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_OBJECT__VALUE = eINSTANCE.getStringObject_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.TypeFaceDefinitionImpl <em>Type Face Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.TypeFaceDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getTypeFaceDefinition()
     * @generated
     */
    EClass TYPE_FACE_DEFINITION = eINSTANCE.getTypeFaceDefinition();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_FACE_DEFINITION__KEY = eINSTANCE.getTypeFaceDefinition_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_FACE_DEFINITION__VALUE = eINSTANCE.getTypeFaceDefinition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.TextStyleDefinitionImpl <em>Text Style Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.TextStyleDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getTextStyleDefinition()
     * @generated
     */
    EClass TEXT_STYLE_DEFINITION = eINSTANCE.getTextStyleDefinition();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_STYLE_DEFINITION__KEY = eINSTANCE.getTextStyleDefinition_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_STYLE_DEFINITION__VALUE = eINSTANCE.getTextStyleDefinition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ItalicsDefinitionImpl <em>Italics Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ItalicsDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getItalicsDefinition()
     * @generated
     */
    EClass ITALICS_DEFINITION = eINSTANCE.getItalicsDefinition();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITALICS_DEFINITION__KEY = eINSTANCE.getItalicsDefinition_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITALICS_DEFINITION__VALUE = eINSTANCE.getItalicsDefinition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.FontSizeDefinitionImpl <em>Font Size Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.FontSizeDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getFontSizeDefinition()
     * @generated
     */
    EClass FONT_SIZE_DEFINITION = eINSTANCE.getFontSizeDefinition();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONT_SIZE_DEFINITION__KEY = eINSTANCE.getFontSizeDefinition_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONT_SIZE_DEFINITION__VALUE = eINSTANCE.getFontSizeDefinition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.StyleDefinitionImpl <em>Style Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.StyleDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyleDefinition()
     * @generated
     */
    EClass STYLE_DEFINITION = eINSTANCE.getStyleDefinition();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE_DEFINITION__KEY = eINSTANCE.getStyleDefinition_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLE_DEFINITION__VALUE = eINSTANCE.getStyleDefinition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.WidthDefinitionImpl <em>Width Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.WidthDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getWidthDefinition()
     * @generated
     */
    EClass WIDTH_DEFINITION = eINSTANCE.getWidthDefinition();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIDTH_DEFINITION__KEY = eINSTANCE.getWidthDefinition_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIDTH_DEFINITION__VALUE = eINSTANCE.getWidthDefinition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ColumnGapDefintionImpl <em>Column Gap Defintion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ColumnGapDefintionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnGapDefintion()
     * @generated
     */
    EClass COLUMN_GAP_DEFINTION = eINSTANCE.getColumnGapDefintion();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_GAP_DEFINTION__KEY = eINSTANCE.getColumnGapDefintion_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_GAP_DEFINTION__VALUE = eINSTANCE.getColumnGapDefintion_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ColumnDefinitionImpl <em>Column Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ColumnDefinitionImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnDefinition()
     * @generated
     */
    EClass COLUMN_DEFINITION = eINSTANCE.getColumnDefinition();

    /**
     * The meta object literal for the '<em><b>Global Style</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_DEFINITION__GLOBAL_STYLE = eINSTANCE.getColumnDefinition_GlobalStyle();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_DEFINITION__KEY = eINSTANCE.getColumnDefinition_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_DEFINITION__VALUE = eINSTANCE.getColumnDefinition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.InnerColumnObjectImpl <em>Inner Column Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.InnerColumnObjectImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getInnerColumnObject()
     * @generated
     */
    EClass INNER_COLUMN_OBJECT = eINSTANCE.getInnerColumnObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INNER_COLUMN_OBJECT__VALUE = eINSTANCE.getInnerColumnObject_Value();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INNER_COLUMN_OBJECT__TEXT = eINSTANCE.getInnerColumnObject_Text();

    /**
     * The meta object literal for the '<em><b>Text Object</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INNER_COLUMN_OBJECT__TEXT_OBJECT = eINSTANCE.getInnerColumnObject_TextObject();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INNER_COLUMN_OBJECT__COLUMN = eINSTANCE.getInnerColumnObject_Column();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ColumnObjectImpl <em>Column Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ColumnObjectImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnObject()
     * @generated
     */
    EClass COLUMN_OBJECT = eINSTANCE.getColumnObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_OBJECT__VALUE = eINSTANCE.getColumnObject_Value();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_OBJECT__TEXT = eINSTANCE.getColumnObject_Text();

    /**
     * The meta object literal for the '<em><b>Text Object</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_OBJECT__TEXT_OBJECT = eINSTANCE.getColumnObject_TextObject();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_OBJECT__COLUMN = eINSTANCE.getColumnObject_Column();

    /**
     * The meta object literal for the '<em><b>Inner Column</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_OBJECT__INNER_COLUMN = eINSTANCE.getColumnObject_InnerColumn();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.TextObjectImpl <em>Text Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.TextObjectImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getTextObject()
     * @generated
     */
    EClass TEXT_OBJECT = eINSTANCE.getTextObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__VALUE = eINSTANCE.getTextObject_Value();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__TEXT = eINSTANCE.getTextObject_Text();

    /**
     * The meta object literal for the '<em><b>Style</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__STYLE = eINSTANCE.getTextObject_Style();

    /**
     * The meta object literal for the '<em><b>Font Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__FONT_SIZE = eINSTANCE.getTextObject_FontSize();

    /**
     * The meta object literal for the '<em><b>Alignment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__ALIGNMENT = eINSTANCE.getTextObject_Alignment();

    /**
     * The meta object literal for the '<em><b>Type Face</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__TYPE_FACE = eINSTANCE.getTextObject_TypeFace();

    /**
     * The meta object literal for the '<em><b>Italics</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__ITALICS = eINSTANCE.getTextObject_Italics();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_OBJECT__WIDTH = eINSTANCE.getTextObject_Width();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ColumnTextObjectImpl <em>Column Text Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ColumnTextObjectImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getColumnTextObject()
     * @generated
     */
    EClass COLUMN_TEXT_OBJECT = eINSTANCE.getColumnTextObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_TEXT_OBJECT__VALUE = eINSTANCE.getColumnTextObject_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.StyleObjectImpl <em>Style Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.StyleObjectImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyleObject()
     * @generated
     */
    EClass STYLE_OBJECT = eINSTANCE.getStyleObject();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE_OBJECT__KEY = eINSTANCE.getStyleObject_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE_OBJECT__VALUE = eINSTANCE.getStyleObject_Value();

    /**
     * The meta object literal for the '<em><b>Font Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE_OBJECT__FONT_SIZE = eINSTANCE.getStyleObject_FontSize();

    /**
     * The meta object literal for the '<em><b>Type Face</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE_OBJECT__TYPE_FACE = eINSTANCE.getStyleObject_TypeFace();

    /**
     * The meta object literal for the '<em><b>Alignment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE_OBJECT__ALIGNMENT = eINSTANCE.getStyleObject_Alignment();

    /**
     * The meta object literal for the '<em><b>Italics</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLE_OBJECT__ITALICS = eINSTANCE.getStyleObject_Italics();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.StyleObjectsImpl <em>Style Objects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.StyleObjectsImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyleObjects()
     * @generated
     */
    EClass STYLE_OBJECTS = eINSTANCE.getStyleObjects();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLE_OBJECTS__VALUE = eINSTANCE.getStyleObjects_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ContentObjectImpl <em>Content Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ContentObjectImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getContentObject()
     * @generated
     */
    EClass CONTENT_OBJECT = eINSTANCE.getContentObject();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTENT_OBJECT__VALUE = eINSTANCE.getContentObject_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ContentObjectsImpl <em>Content Objects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ContentObjectsImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getContentObjects()
     * @generated
     */
    EClass CONTENT_OBJECTS = eINSTANCE.getContentObjects();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTENT_OBJECTS__VALUE = eINSTANCE.getContentObjects_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.StylesImpl <em>Styles</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.StylesImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getStyles()
     * @generated
     */
    EClass STYLES = eINSTANCE.getStyles();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STYLES__KEY = eINSTANCE.getStyles_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLES__VALUE = eINSTANCE.getStyles_Value();

    /**
     * The meta object literal for the '{@link org.xtext.avi.pdfMk.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.avi.pdfMk.impl.ContentImpl
     * @see org.xtext.avi.pdfMk.impl.PdfMkPackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__KEY = eINSTANCE.getContent_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTENT__VALUE = eINSTANCE.getContent_Value();

  }

} //PdfMkPackage
