/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Style Object Members Wrapper</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.avi.pdfMk.PdfMkPackage#getStyleObjectMembersWrapper()
 * @model
 * @generated
 */
public interface StyleObjectMembersWrapper extends EObject
{
} // StyleObjectMembersWrapper
