/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isText <em>Text</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isStyle <em>Style</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isFontSize <em>Font Size</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isAlignment <em>Alignment</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isTypeFace <em>Type Face</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isItalics <em>Italics</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isWidth <em>Width</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isMargin <em>Margin</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.TextObject#isListCounter <em>List Counter</em>}</li>
 * </ul>
 *
 * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject()
 * @model
 * @generated
 */
public interface TextObject extends ListElements
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_Text()
   * @model
   * @generated
   */
  boolean isText();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #isText()
   * @generated
   */
  void setText(boolean value);

  /**
   * Returns the value of the '<em><b>Style</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Style</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Style</em>' attribute.
   * @see #setStyle(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_Style()
   * @model
   * @generated
   */
  boolean isStyle();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isStyle <em>Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Style</em>' attribute.
   * @see #isStyle()
   * @generated
   */
  void setStyle(boolean value);

  /**
   * Returns the value of the '<em><b>Font Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Font Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Font Size</em>' attribute.
   * @see #setFontSize(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_FontSize()
   * @model
   * @generated
   */
  boolean isFontSize();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isFontSize <em>Font Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Font Size</em>' attribute.
   * @see #isFontSize()
   * @generated
   */
  void setFontSize(boolean value);

  /**
   * Returns the value of the '<em><b>Alignment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alignment</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alignment</em>' attribute.
   * @see #setAlignment(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_Alignment()
   * @model
   * @generated
   */
  boolean isAlignment();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isAlignment <em>Alignment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alignment</em>' attribute.
   * @see #isAlignment()
   * @generated
   */
  void setAlignment(boolean value);

  /**
   * Returns the value of the '<em><b>Type Face</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Face</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Face</em>' attribute.
   * @see #setTypeFace(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_TypeFace()
   * @model
   * @generated
   */
  boolean isTypeFace();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isTypeFace <em>Type Face</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Face</em>' attribute.
   * @see #isTypeFace()
   * @generated
   */
  void setTypeFace(boolean value);

  /**
   * Returns the value of the '<em><b>Italics</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Italics</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Italics</em>' attribute.
   * @see #setItalics(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_Italics()
   * @model
   * @generated
   */
  boolean isItalics();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isItalics <em>Italics</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Italics</em>' attribute.
   * @see #isItalics()
   * @generated
   */
  void setItalics(boolean value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_Width()
   * @model
   * @generated
   */
  boolean isWidth();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #isWidth()
   * @generated
   */
  void setWidth(boolean value);

  /**
   * Returns the value of the '<em><b>Margin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Margin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Margin</em>' attribute.
   * @see #setMargin(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_Margin()
   * @model
   * @generated
   */
  boolean isMargin();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isMargin <em>Margin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Margin</em>' attribute.
   * @see #isMargin()
   * @generated
   */
  void setMargin(boolean value);

  /**
   * Returns the value of the '<em><b>List Counter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List Counter</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Counter</em>' attribute.
   * @see #setListCounter(boolean)
   * @see org.xtext.avi.pdfMk.PdfMkPackage#getTextObject_ListCounter()
   * @model
   * @generated
   */
  boolean isListCounter();

  /**
   * Sets the value of the '{@link org.xtext.avi.pdfMk.TextObject#isListCounter <em>List Counter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Counter</em>' attribute.
   * @see #isListCounter()
   * @generated
   */
  void setListCounter(boolean value);

} // TextObject
