/*
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.avi.pdfmake_dsl.ui.internal.Pdfmake_dslActivator;

public class PdfMkUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Pdfmake_dslActivator.getInstance().getInjector("org.xtext.avi.PdfMk");
	}

}
