/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.avi.pdfMk.ColumnDefinition;
import org.xtext.avi.pdfMk.ColumnObject;
import org.xtext.avi.pdfMk.InnerColumnObject;
import org.xtext.avi.pdfMk.PdfMkPackage;
import org.xtext.avi.pdfMk.StringObject;
import org.xtext.avi.pdfMk.TextObject;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Column Object</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ColumnObjectImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ColumnObjectImpl#getText <em>Text</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ColumnObjectImpl#getTextObject <em>Text Object</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ColumnObjectImpl#getColumn <em>Column</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ColumnObjectImpl#getInnerColumn <em>Inner Column</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ColumnObjectImpl extends MinimalEObjectImpl.Container implements ColumnObject
{
  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getText() <em>Text</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected EList<StringObject> text;

  /**
   * The cached value of the '{@link #getTextObject() <em>Text Object</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTextObject()
   * @generated
   * @ordered
   */
  protected EList<TextObject> textObject;

  /**
   * The cached value of the '{@link #getColumn() <em>Column</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumn()
   * @generated
   * @ordered
   */
  protected EList<ColumnDefinition> column;

  /**
   * The cached value of the '{@link #getInnerColumn() <em>Inner Column</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInnerColumn()
   * @generated
   * @ordered
   */
  protected EList<InnerColumnObject> innerColumn;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ColumnObjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PdfMkPackage.Literals.COLUMN_OBJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PdfMkPackage.COLUMN_OBJECT__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<StringObject> getText()
  {
    if (text == null)
    {
      text = new EObjectContainmentEList<StringObject>(StringObject.class, this, PdfMkPackage.COLUMN_OBJECT__TEXT);
    }
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<TextObject> getTextObject()
  {
    if (textObject == null)
    {
      textObject = new EObjectContainmentEList<TextObject>(TextObject.class, this, PdfMkPackage.COLUMN_OBJECT__TEXT_OBJECT);
    }
    return textObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ColumnDefinition> getColumn()
  {
    if (column == null)
    {
      column = new EObjectContainmentEList<ColumnDefinition>(ColumnDefinition.class, this, PdfMkPackage.COLUMN_OBJECT__COLUMN);
    }
    return column;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<InnerColumnObject> getInnerColumn()
  {
    if (innerColumn == null)
    {
      innerColumn = new EObjectContainmentEList<InnerColumnObject>(InnerColumnObject.class, this, PdfMkPackage.COLUMN_OBJECT__INNER_COLUMN);
    }
    return innerColumn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PdfMkPackage.COLUMN_OBJECT__TEXT:
        return ((InternalEList<?>)getText()).basicRemove(otherEnd, msgs);
      case PdfMkPackage.COLUMN_OBJECT__TEXT_OBJECT:
        return ((InternalEList<?>)getTextObject()).basicRemove(otherEnd, msgs);
      case PdfMkPackage.COLUMN_OBJECT__COLUMN:
        return ((InternalEList<?>)getColumn()).basicRemove(otherEnd, msgs);
      case PdfMkPackage.COLUMN_OBJECT__INNER_COLUMN:
        return ((InternalEList<?>)getInnerColumn()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PdfMkPackage.COLUMN_OBJECT__VALUE:
        return getValue();
      case PdfMkPackage.COLUMN_OBJECT__TEXT:
        return getText();
      case PdfMkPackage.COLUMN_OBJECT__TEXT_OBJECT:
        return getTextObject();
      case PdfMkPackage.COLUMN_OBJECT__COLUMN:
        return getColumn();
      case PdfMkPackage.COLUMN_OBJECT__INNER_COLUMN:
        return getInnerColumn();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PdfMkPackage.COLUMN_OBJECT__VALUE:
        setValue((String)newValue);
        return;
      case PdfMkPackage.COLUMN_OBJECT__TEXT:
        getText().clear();
        getText().addAll((Collection<? extends StringObject>)newValue);
        return;
      case PdfMkPackage.COLUMN_OBJECT__TEXT_OBJECT:
        getTextObject().clear();
        getTextObject().addAll((Collection<? extends TextObject>)newValue);
        return;
      case PdfMkPackage.COLUMN_OBJECT__COLUMN:
        getColumn().clear();
        getColumn().addAll((Collection<? extends ColumnDefinition>)newValue);
        return;
      case PdfMkPackage.COLUMN_OBJECT__INNER_COLUMN:
        getInnerColumn().clear();
        getInnerColumn().addAll((Collection<? extends InnerColumnObject>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PdfMkPackage.COLUMN_OBJECT__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case PdfMkPackage.COLUMN_OBJECT__TEXT:
        getText().clear();
        return;
      case PdfMkPackage.COLUMN_OBJECT__TEXT_OBJECT:
        getTextObject().clear();
        return;
      case PdfMkPackage.COLUMN_OBJECT__COLUMN:
        getColumn().clear();
        return;
      case PdfMkPackage.COLUMN_OBJECT__INNER_COLUMN:
        getInnerColumn().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PdfMkPackage.COLUMN_OBJECT__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
      case PdfMkPackage.COLUMN_OBJECT__TEXT:
        return text != null && !text.isEmpty();
      case PdfMkPackage.COLUMN_OBJECT__TEXT_OBJECT:
        return textObject != null && !textObject.isEmpty();
      case PdfMkPackage.COLUMN_OBJECT__COLUMN:
        return column != null && !column.isEmpty();
      case PdfMkPackage.COLUMN_OBJECT__INNER_COLUMN:
        return innerColumn != null && !innerColumn.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //ColumnObjectImpl
