/**
 * generated by Xtext 2.16.0
 */
package org.xtext.avi.pdfMk.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.avi.pdfMk.ListElements;
import org.xtext.avi.pdfMk.ListObject;
import org.xtext.avi.pdfMk.ListObjectPropertiesWrapper;
import org.xtext.avi.pdfMk.PdfMkPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>List Object</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ListObjectImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ListObjectImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ListObjectImpl#getElements <em>Elements</em>}</li>
 *   <li>{@link org.xtext.avi.pdfMk.impl.ListObjectImpl#getElemtens <em>Elemtens</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ListObjectImpl extends MinimalEObjectImpl.Container implements ListObject
{
  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<ListObjectPropertiesWrapper> properties;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<ListElements> elements;

  /**
   * The cached value of the '{@link #getElemtens() <em>Elemtens</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElemtens()
   * @generated
   * @ordered
   */
  protected EList<ListElements> elemtens;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListObjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PdfMkPackage.Literals.LIST_OBJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PdfMkPackage.LIST_OBJECT__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ListObjectPropertiesWrapper> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<ListObjectPropertiesWrapper>(ListObjectPropertiesWrapper.class, this, PdfMkPackage.LIST_OBJECT__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ListElements> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<ListElements>(ListElements.class, this, PdfMkPackage.LIST_OBJECT__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ListElements> getElemtens()
  {
    if (elemtens == null)
    {
      elemtens = new EObjectContainmentEList<ListElements>(ListElements.class, this, PdfMkPackage.LIST_OBJECT__ELEMTENS);
    }
    return elemtens;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PdfMkPackage.LIST_OBJECT__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
      case PdfMkPackage.LIST_OBJECT__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
      case PdfMkPackage.LIST_OBJECT__ELEMTENS:
        return ((InternalEList<?>)getElemtens()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PdfMkPackage.LIST_OBJECT__VALUE:
        return getValue();
      case PdfMkPackage.LIST_OBJECT__PROPERTIES:
        return getProperties();
      case PdfMkPackage.LIST_OBJECT__ELEMENTS:
        return getElements();
      case PdfMkPackage.LIST_OBJECT__ELEMTENS:
        return getElemtens();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PdfMkPackage.LIST_OBJECT__VALUE:
        setValue((String)newValue);
        return;
      case PdfMkPackage.LIST_OBJECT__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends ListObjectPropertiesWrapper>)newValue);
        return;
      case PdfMkPackage.LIST_OBJECT__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends ListElements>)newValue);
        return;
      case PdfMkPackage.LIST_OBJECT__ELEMTENS:
        getElemtens().clear();
        getElemtens().addAll((Collection<? extends ListElements>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PdfMkPackage.LIST_OBJECT__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case PdfMkPackage.LIST_OBJECT__PROPERTIES:
        getProperties().clear();
        return;
      case PdfMkPackage.LIST_OBJECT__ELEMENTS:
        getElements().clear();
        return;
      case PdfMkPackage.LIST_OBJECT__ELEMTENS:
        getElemtens().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PdfMkPackage.LIST_OBJECT__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
      case PdfMkPackage.LIST_OBJECT__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case PdfMkPackage.LIST_OBJECT__ELEMENTS:
        return elements != null && !elements.isEmpty();
      case PdfMkPackage.LIST_OBJECT__ELEMTENS:
        return elemtens != null && !elemtens.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //ListObjectImpl
